# Site settings
title: Philipp Wesner
header-img: img/home-bg.jpg
email: pwesner@innomind.de
description: "Blog about Ruby on Rails developemnt, Entrepreneurship and Math"
# baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://wasi.github.io"
twitter_username: philippwesner
github_username:  wasi
facebook_username:  philipp.wesner.9

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
